export const migration001 = `
-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS budgets (
    guid character varying(36) PRIMARY KEY,
    active boolean NOT NULL DEFAULT true,
    fullname character varying(50) NOT NULL,
    username character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    "dateLastLogin" timestamp with time zone,
    "dateCreated" timestamp with time zone NOT NULL DEFAULT now(),
    "dateModified" timestamp with time zone NOT NULL DEFAULT now(),
    starting_balance numeric(10,2) NOT NULL DEFAULT 0.00,
    email character varying(50) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS budgets_pkey ON budgets(guid text_ops);
`;
