export const migration006 = `
-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS subcategories (
    guid character varying(36) PRIMARY KEY,
    category_guid character varying(36) NOT NULL REFERENCES categories(guid) ON DELETE CASCADE,
    label character varying(50) NOT NULL DEFAULT ''::character varying,
    "dateCreated" timestamp with time zone NOT NULL DEFAULT now(),
    "dateModified" timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE items
    ADD subcategory_guid character varying(36) REFERENCES subcategory(guid);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS subcategories_pkey ON subcategories(guid text_ops,category_guid text_ops);
`;
