-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    guid character varying(36),
    budget_guid character varying(36),
    active boolean NOT NULL DEFAULT true,
    fullname character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    "dateLastLogin" timestamp with time zone,
    "dateCreated" timestamp with time zone NOT NULL DEFAULT now(),
    "dateModified" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (guid, budget_guid)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX users_pkey ON users(guid text_ops,budget_guid text_ops);