name: Deploy API

on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - labeled

env:
  AWS_REGION: us-east-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.15.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Install
        shell: bash
        working-directory: packages/budget-api
        run: npm i

      - name: Test
        working-directory: packages/budget-api
        run: npm run test

  deploy:
    if: ((github.event_name == 'pull_request') && (github.event.label.name == 'deploy api')) || (github.event_name == 'push' && github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          aws-region: ${{ env.AWS_REGION }}
           
      - name: Update NPM
        run: sudo npm install -g npm@8.1.0

      - name: Install CDK
        run: sudo npm install -g aws-cdk

      - name: Install
        id: install
        working-directory: packages/budget-api
        run: |
          npm i

      - name: Version and publish package
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: Tom Mollerus
          GIT_AUTHOR_EMAIL: tom@mollerus.net
          GIT_COMMITTER_NAME: Tom Mollerus
          GIT_COMMITTER_EMAIL: tom@mollerus.net
        working-directory: packages/budget-ui
        run: npx semantic-release -e semantic-release-monorepo

      - name: Setup package and build
        id: build
        working-directory: packages/budget-api
        run: |
          npm run build

      - name: Deploy
        id: deploy
        working-directory: packages/budget-api
        env:
          ENV_NAME: production
          CORS_DOMAINS: https://budget.mollerus.net
          DOMAIN_NAME: budget-api.mollerus.net
        run: cdk deploy --require-approval=never

      - name: Create changeset if deploy failed
        if: ${{ failure() && steps.deploy.conclusion == 'failure' }}
        id: changeset
        working-directory: packages/budget-api
        run: cdk deploy --require-approval=never --no-execute

      - name: If change-set created, comment on PR
        if: ${{ success() && steps.changeset.conclusion == 'success' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GH_TOKEN }}
          body: |
            I failed to deploy your stack.`.
            Here is a [change-set](${{ steps.change_set.outputs.change_set_url }}) that you must execute manually to deploy your application. Please contact a manager to execute the change-set.
